from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from datetime import datetime

def generate_cam(company_data, metrics, ratios, fraud_result, risk_result, factors):
    filename = f"CAM_{company_data['name'].replace(' ','_')}_{datetime.now().strftime('%Y%m%d')}.pdf"
    doc    = SimpleDocTemplate(filename, pagesize=A4)
    styles = getSampleStyleSheet()
    story  = []

    # Title
    story.append(Paragraph(
        "CREDIT APPRAISAL MEMO (CAM)", styles["Title"]
    ))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%d %B %Y')} | Confidential",
        styles["Normal"]
    ))
    story.append(Spacer(1, 0.2*inch))

    # Company info
    story.append(Paragraph("1. BORROWER INFORMATION", styles["Heading2"]))
    company_table_data = [
        ["Company Name",  company_data["name"]],
        ["Sector",        company_data.get("sector", "N/A")],
        ["Loan Requested",f"₹{company_data.get('loan_amount', 'N/A')} Crores"],
        ["Loan Tenure",   f"{company_data.get('tenure', 'N/A')} months"],
    ]
    t = Table(company_table_data, colWidths=[2.5*inch, 3.5*inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#E6F1FB")),
        ("FONTNAME",   (0,0), (0,-1), "Helvetica-Bold"),
        ("GRID",       (0,0), (-1,-1), 0.5, colors.grey),
        ("PADDING",    (0,0), (-1,-1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.2*inch))

    # Financial summary
    story.append(Paragraph("2. FINANCIAL SUMMARY", styles["Heading2"]))
    fin_data = [["Metric", "Value"]] + [
        [k.replace("_"," ").title(), str(v)]
        for k, v in {**metrics, **ratios}.items()
    ]
    ft = Table(fin_data, colWidths=[3*inch, 3*inch])
    ft.setStyle(TableStyle([
        ("BACKGROUND",  (0,0), (-1,0), colors.HexColor("#2B5C8A")),
        ("TEXTCOLOR",   (0,0), (-1,0), colors.white),
        ("FONTNAME",    (0,0), (-1,0), "Helvetica-Bold"),
        ("GRID",        (0,0), (-1,-1), 0.5, colors.grey),
        ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, colors.HexColor("#F5F5F5")]),
        ("PADDING",     (0,0), (-1,-1), 6),
    ]))
    story.append(ft)
    story.append(Spacer(1, 0.2*inch))

    # Risk assessment
    story.append(Paragraph("3. RISK ASSESSMENT", styles["Heading2"]))
    risk_color = colors.HexColor("#D85A30") if risk_result["risk_level"] == "HIGH" \
                 else colors.HexColor("#EF9F27") if risk_result["risk_level"] == "MEDIUM" \
                 else colors.HexColor("#1D9E75")
    story.append(Paragraph(
        f"Credit Score: {risk_result['credit_score']}/100 | "
        f"Risk Level: {risk_result['risk_level']}",
        styles["Normal"]
    ))
    story.append(Spacer(1, 0.1*inch))

    # Key factors
    story.append(Paragraph("Key Factors Driving Decision:", styles["Heading3"]))
    for f in factors[:4]:
        color = "red" if f["impact"] == "INCREASES RISK" else "green"
        story.append(Paragraph(
            f"• {f['feature']}: {f['value']} → {f['impact']}",
            styles["Normal"]
        ))
    story.append(Spacer(1, 0.15*inch))

    # Fraud signals
    story.append(Paragraph("4. FRAUD DETECTION SUMMARY", styles["Heading2"]))
    story.append(Paragraph(
        f"Fraud Risk: {fraud_result['risk_level']} (Score: {fraud_result['fraud_score']}/100)",
        styles["Normal"]
    ))
    if fraud_result["flags"]:
        for flag in fraud_result["flags"]:
            story.append(Paragraph(f"⚠ {flag['signal']}: {flag['detail']}", styles["Normal"]))
    else:
        story.append(Paragraph("✓ No fraud signals detected.", styles["Normal"]))
    story.append(Spacer(1, 0.2*inch))

    # Final recommendation
    story.append(Paragraph("5. RECOMMENDATION", styles["Heading2"]))
    decision = risk_result["approval"]
    story.append(Paragraph(
        f"Decision: {decision}",
        styles["Heading2"]
    ))
    if decision == "APPROVED":
        rec_amount = company_data.get("loan_amount", 0) * 0.8
        story.append(Paragraph(f"Recommended Amount: ₹{rec_amount:.1f} Crores", styles["Normal"]))
        story.append(Paragraph(f"Suggested Rate: {10.5 + (risk_result['risk_probability']*3):.1f}%", styles["Normal"]))
    story.append(Spacer(1, 0.1*inch))
    story.append(Paragraph(
        "This CAM is auto-generated by Intelli-Credit AI Platform. "
        "Final decision rests with the credit committee.",
        styles["Normal"]
    ))

    doc.build(story)
    return filename